services:
  stats-server:
    build: ./stats
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=statsdb
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS_URL=http://stats-server:9090

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=statsdb
      - POSTGRES_DB=statsdb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./main
    container_name: main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/maindb
      - SPRING_DATASOURCE_USERNAME=maindb
      - SPRING_DATASOURCE_PASSWORD=12345

  ewm-db:
    image: postgres:16.1
    container_name: main-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=maindb
      - POSTGRES_DB=maindb
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
